### ISSUE TITLE
Regular expressions (with capturing groups) in URL mapping

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#10]
e.g 
    Application application = new Application(
        new HashMap<String, RequestHandler>() 
            {{ put("/person/([0-9]+)", new MyRequestHandler()); }}
    );

The number [0-9]+ is inside a capturing group and should be delivered to the associated RequestHandler

**Comment by rschildmeijer** [comment]
Design proposal 1: augment RH.{get, post, put, delete} with an additional (third) parameter; String args... (which will be null if no capturing groups are present).

Design proposal 2: expose a new method in HttpRequest, e.g.String[] getCapturingGroups or/and String getCapturingGroup(int index).

**Comment by rschildmeijer** [comment]
Prepared org.deft.web.Application for capturing groups in commit 055f6166a90a3fc6a067. 
Will not continue on this issue until feedback is given

**Comment by jimpetersson** [comment]
Looks good. Carry on..

**Comment by rschildmeijer** [comment]
feedback again please

**Comment by rschildmeijer** [comment]
concerns: 1, naming (e.g, handlers, capturingHandlers, regexps). 2, "leak" PatternSyntaxException if client supplies malformed regex

**Comment by jimpetersson** [comment]
I would like to see this more documented. Some more comments in code, describing eag immutableMap for instance.
Might also be good to start "proper" documentation for deft and and info about CapturingGroups.
I think we could start the documentation on the wiki-page?

**Comment by rschildmeijer** [comment]
I agree. Added doc in code. Better(?) field names for the immutable maps

**Comment by schildmeijer** [comment]
Added "group captuing with regular expressions". Closed by d184d1c56d20102032c35c95175ef0f276260f1f
