### ISSUE TITLE
HttpRequest Does Not Parse "RequestedPath" Correctly

### ISSUE THREAD

**Issue by nickman** [rschildmeijer/deft#104]
I think there is a problem with the Deft HttpRequest parsing, specifically with the value of the requestedPath attribute.
I believe this value should be the URI up to but not including the query string. Currently, the return value for getRequestedPath returns the full request line, including the query string.

For example:  /foo?a=XXX&y=ZZZ
Currently Returns: /foo?a=XXX&y=ZZZ
Should Return: /foo

This has the secondary effect of breaking request handler mappings since any addition of a query string will result in a request handler for /foo not being found.

I patched this locally as follows:

```
public HttpRequest(String requestLine, Map<String, String> headers) {
    this.requestLine = requestLine;
    String[] elements = requestLine.split(" ");
    method = HttpVerb.valueOf(elements[0]);
    String[] pathFrags = elements[1].split("\\?");
    requestedPath = pathFrags[0];
    version = elements[2];
    this.headers = headers;   
    body = null;
    initKeepAlive();
    parameters = parseParameters(elements[1]);
}
```

**Comment by rschildmeijer** [comment]
Implements #104 (HttpRequest Does Not Parse &quot;RequestedPath&quot; Correctly) (closed by c4bf2e0451dbfdcc87cf81022ba100bcfe3661c0)
patch by Nicholas Whitehead and rschildmeijer reviewed by rschildmeijer
