### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#13]
How should exceptions be handled, which log should be written to etc.

**Comment by rschildmeijer** [comment]
request for clarification

**Comment by jimpetersson** [comment]
We just need to have som general guidelines how we should handle exceptions.
As it is now, sometimes we just call exception.printStackTrace, sometimes we log to stdout etc.
For now i think it would be sufficiient if we just would add another logging appender, which writes to a file (deft.log)

**Comment by rschildmeijer** [comment]
ah yes, ofcourse. e.printStackTrace feels wrong :)

**Comment by rschildmeijer** [comment]
reject; work as intented

**Comment by rschildmeijer** [comment]
.
