### ISSUE TITLE
 java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by ilmich** [rschildmeijer/deft#135]
Hi, during load test with static files I get this exception:

java.io.IOException: Too many open files
sun.nio.ch.ServerSocketChannelImpl.accept0 at (Native Method) ~ [na na]
at sun.nio.ch.ServerSocketChannelImpl.accept (ServerSocketChannelImpl.java: 152) ~ [na na]
at org.deftserver.web.http.HttpProtocol.handleAccept (HttpProtocol.java: 43) ~ [bin / na]
at org.deftserver.io.IOLoop.start (IOLoop.java: 78) ~ [bin / na]
at it.meebookto.webserver.MainServer.main (MainServer.java: 25)

It seems that the method 

HttpResponse.write (File file) 

does not release resources after reading from the file system.
Sorry for my bad english:)

**Comment by rschildmeijer** [comment]
The number of open files descriptors allowed is an operating system dependent configuration. This value is often too low.
So I recommend to raise that limit and run the tests again. If you are running on Linux this page describes the step to increase the fd limit: http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

Also I would like to remind you about the status (in release 0.3.0) of the "static file server" component in Deft. 
- It's "Experimental support" (as stated in the javadoc).
- No support for large static files (https://github.com/rschildmeijer/deft/issues/75)
- "In production, you probably want to serve static files from a more optimized static file server like nginx." (currently undocumented on deftserver.org)

**Comment by ilmich** [comment]
I had already raised the limit of the number of files allowed, but I get the error with a simple

ab-c 25-n 1000 http://localhost:9080/static/somefile.txt

and then I'm thinking that the resources are never released.
I made a simple fix on the method HttpResponse.Write (File), which simply closes the RandomAccessFile object and everything works perfectly:)

I know that the file support is experimental, but for my project I would like to use software completely written in Java, where possible, and your project is just what I wanted!

Thank you for your work.

**Comment by rschildmeijer** [comment]
Yes you are right, we are leaking file descriptors during static file serving. Thanks for the research :)
Do you mind submitting a patch on the mailing list (deft-web-server@googlegroups.com) or here and I will review and commit the fix.

**Comment by ilmich** [comment]
I think that i will create a fork of your project in order to submit this fix and other things that I'm developing(simple cookie handling, more information of the remote client in the HttpRequest class, simple Http Session creation and handling, integration with JGroups and some other stuff ^__^ )

**Comment by rschildmeijer** [comment]
Feel free to fork the project :)
Regarding: 
- simple cookie handling
    I know that johnathanmeehan (https://github.com/johnathanmeehan) has made some great progress on a cookie
    implementation (https://github.com/rschildmeijer/deft/issues/52) on his Deft fork. Its somewhere about 75-100% done.
    So I would recommend to take a look at that before start rolling your own.
- more info in HttpRequest
   I've been thinking about this for some time but never created the issue for it. Feel free to create an issue and define
   what could be of interest (e.g. remote address etc)
- http sessions
   could also be worth an issue by itself.
- Jgroups integration
    know I did some Jgroups research when I tried Hazelcast. Looked pretty ok.
