### ISSUE TITLE
Persistent connections

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#15]
Connection keep-alive
http://bit.ly/VopwT

**Comment by rschildmeijer** [comment]
"In HTTP 1.1 all connections are considered persistent, unless declared otherwise" (Connection: close) from wikipedia

"If either the client or the server sends the close token in the Connection header, that request becomes the last one for the connection" (from url above)

**Comment by jimpetersson** [comment]
" An HTTP/1.1 server MAY assume that a HTTP/1.1 client intends to maintain a persistent connection unless a Connection header including the connection-token "close" was sent in the request. If the server chooses to close the connection immediately after sending the response, it SHOULD send a Connection header including the connection-token close."

"An HTTP/1.1 client MAY expect a connection to remain open, but would decide to keep it open based on whether the response from a server contains a Connection header with the connection-token close. In case the client does not want to maintain a connection for more than that request, it SHOULD send a Connection header including the connection-token close."

(From: http://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html)

**Comment by rschildmeijer** [comment]
patch ready for review mailed.

**Comment by jimpetersson** [comment]
Reviewed and pushed with minor modifications.
Before we can close this issue we must fix so that Http 1.0 requests doesn't get treated as Persistent connections. (They are per definition non-persistent)

Design proposal: 
Add this check in HttpRequest.initKeepAlive()

**Comment by jimpetersson** [comment]
Also, we probably should add some code so that persistent connections are "cleaned up" every 'n' seconds or so. Current implementation will never clean up old connections if server load is high

**Comment by schildmeijer** [comment]
Last part for #15 (persistent connections). Handling http version1.0 requests, clean up connections properly during high load. closed by cadab695ec438bcf6423bc174a57d023183edf46
