### ISSUE TITLE
Optimize HttpUtil.createInitialLine()

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#19]
Remove String concatenation

**Comment by rschildmeijer** [comment]
createHttpHeader is split into two methods; createInitialLineAndHeaders and createInitialLine.
Reason: former name was misleading because it did mention the creation of the initial response line (e.g HTTP/1.1 200 OK)

**Comment by rschildmeijer** [comment]
We could probably create private static final Strings instead.

**Comment by schildmeijer** [comment]
Implemented #19 (Optimize HttpUtil.createInitialLine() ) Closed by 2d90e8d58cbd0b817ce55b5e2567124a98632614
