### ISSUE TITLE
Better looking 404-page

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#20]
Fix content of 404 page

**Comment by rschildmeijer** [comment]
"many web servers by default issue an HTML page that includes both the 404 code and the "Not Found" phrase." from wikipedia: http://en.wikipedia.org/wiki/HTTP_404

**Comment by jimpetersson** [comment]
That's pretty much what we do now.
Ok for now? Close?

**Comment by rschildmeijer** [comment]
yes close

**Comment by jimpetersson** [comment]
.
