### ISSUE TITLE
StaticContentHandler

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#21]
Implement requesthandler that delivers static content

**Comment by rschildmeijer** [comment]
rename to StaticContentResouceHandler?

**Comment by rschildmeijer** [comment]
#28 should probably be done in conjunction with this issue

**Comment by jimpetersson** [comment]
First draft pushed.
More work to be done...

**Comment by rschildmeijer** [comment]
Could try using RandomAccessFile.transferTo(long position, long count, WritableByteChannel target)  to solve the current http payload problem. 

If that solves our issues i propose the following design: 
1, overload HttpResponse.write(File file).
2, in write  do RandomAccessFile raf = new RandomAccessFile(file);
raf.getChannel().transferTo(0, raf.size(), clientChannel); after initial line and headers are written to wire.

about transferTo (thanks williame)
"This method is potentially much more efficient than a simple loop that reads from this channel and writes to the target channel. Many operating systems can transfer bytes directly from the filesystem cache to the target channel without actually copying them."

**Comment by schildmeijer** [comment]
Last pieces of #21 (StaticContentHandler) and #28 (Handle If-Modified-Since) (closed by f12cf0b2d76ca8cab499533bb11d8584fa5557c9) (closed by f12cf0b2d76ca8cab499533bb11d8584fa5557c9)
