### ISSUE TITLE
Dispatch on correct method in HttpProtocolImpl.handleRead()

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#22]
Right now it's assumed that it's the GET method.
Need to check wheter it's GET/POST/HEAD etc. and then call corresponding method on RH

**Comment by jimpetersson** [comment]
Should be fixed with new HttpRequestDispatcher.
Close this issue?

**Comment by rschildmeijer** [comment]
Yes

**Comment by jimpetersson** [comment]
Done
