### ISSUE TITLE
Return 501 for unimplemented methods 

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#26]
Supporting the GET and HEAD methods

To comply with HTTP 1.1, a server must support at least the GET and HEAD methods. If you're handling CGI scripts, you should probably support the POST method too.

Four other methods (PUT, DELETE, OPTIONS, and TRACE) are defined in HTTP 1.1, but are rarely used. If a client requests a method you don't support, respond with "501 Not Implemented", like

```
HTTP/1.1 501 Not Implemented
[blank line here]
```

See: http://www.jmarshall.com/easy/http/#http1.1s8

**Comment by jimpetersson** [comment]
I think sending a 501 page should be the default implementation of the Http methods in RequestHandler.

**Comment by rschildmeijer** [comment]
+1 on this design proposal

**Comment by jimpetersson** [comment]
Implemented
