### ISSUE TITLE
Supporting HTTP 1.0 Requests

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#27]
To be compatible with older browsers, HTTP 1.1 servers must support HTTP 1.0 requests. In particular, when a request uses HTTP 1.0 (as identified in the initial request line),

```
* don't require the Host: header, and
* don't send the "100 Continue" response. 
```

See: http://www.jmarshall.com/easy/http/#http1.1s8

**Comment by rschildmeijer** [comment]
Seems cheap and like a no brainer to support. So go for it.

**Comment by jimpetersson** [comment]
First "rule" fixed. We don't require the Host header for http 1.0

**Comment by jimpetersson** [comment]
As it is now we never send a "100 Continue" so as far as this issue goes we are ok.
If we in future decides to implement the 100 response we have to make sure that it's never sent to Http.1.0 clients though.
