### ISSUE TITLE
Accepting Absolute URL's

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#30]
The Host: header is actually an interim solution to the problem of host identification. In future versions of HTTP, requests will use an absolute URL instead of a pathname, like

```
GET http://www.somehost.com/path/file.html HTTP/1.2
```

To enable this protocol transition, HTTP 1.1 servers must accept this form of request, even though HTTP 1.1 clients won't send them. The server must still report an error if an HTTP 1.1 client leaves out the Host: header

See: http://www.jmarshall.com/easy/http/#http1.1s8

**Comment by jimpetersson** [comment]
I say we fix this when Http 1.2 arrives..
Close?

**Comment by rschildmeijer** [comment]
yes, closed.
