### ISSUE TITLE
Default HTTP headers

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#33]
In HttpUtil.createInitialLineAndHeaders we (currently) have two default headers -- Server and Date  

Verify what http headers we should have as default.

**Comment by jimpetersson** [comment]
Current implementation sets two headers:
Server: 
Date:

This should be sufficient for now, but later on we probably want to set content-type and content-length

**Comment by jimpetersson** [comment]
Added comment about Http-headers in response.
Closed by bc7c0e5a0b0b98bace3fda362caeb1d167a40427
