### ISSUE TITLE
Http GET query parameters

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#35]
e.g. http://127.0.0.1:8080/person?name=roger&surname=schildmeijer

API proposal: HttpRequest.getParameter(String parameterName);
e.g String name = request.getParameter("name");  // name == "roger"

**Comment by jimpetersson** [comment]
How about a Map<String, String> params = HttpRequest.getParameters(); ?

**Comment by rschildmeijer** [comment]
Map<String, String>  HttpRequest.getParameters() +
String HttpRequest.getParameter(String parameterName) looks very much like the java servlet api iirc. good or bad ;) ?

**Comment by jimpetersson** [comment]
First draft commited.
Right now only & is supported as parameter delimiter: 
/path?param1=value1&param2=value2

We also need to support ; as delim:
/path?param1=value1;param2=value2

**Comment by jimpetersson** [comment]
Also, we should add support for multiple values for a single parameter:
/path?param1=value1;param1=value2

**Comment by rschildmeijer** [comment]
i think this is fine for now. close?

**Comment by jimpetersson** [comment]
I think we should add support for ; delimiter first

**Comment by rschildmeijer** [comment]
ok,maybe we should add support for multiple values in this issue also?
dont forget to add unit tests and/or system tests before closing this issue :)

**Comment by jimpetersson** [comment]
You are right, we should do multiple values as well. (and create tests for it.. )

**Comment by jimpetersson** [comment]
Support for semicolon delimiter fixed

**Comment by jimpetersson** [comment]
Implemented multi-value GET-parameters.
Closed by c0282f837c47288df89d87c922e715ab83dcc291
