### ISSUE TITLE
Support for multiple writes

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#37]
We should support multiple invocations to HttpResponse.write instead of the current limitation where we only support one single call to write. If another call is made a MultipleWritesException is thrown.

Beginning of HttpResponse.write: 
    if (writeExecuted) {
      throw new MultipleWritesException();
    }

We could introduce a new method called 'flush' which pretty much does what write does today (i.e write initial response line and headers and then send the data).

write could buffer things up in memory until next flush invocation.

finish could do a flush + close connection

**Comment by jimpetersson** [comment]
Implemented flush method. Write can now be called multiple times.
First call to flush will add "initial line" and headers.
finish will always make a call to flush. So for an RH method that is not marked with Asyncronous it's sufficient to do like this:
response.write("hello");

Have a look at it and see what you think, probably needs some "tweaking"

**Comment by rschildmeijer** [comment]
Looks good. I think we can close this issue we add some unit tests / system tests using RH with @Asynchronous annotations. (hint org.deft.web.DeftSystemTests).

The important part with the unit test is to have a test that verifies scenarios much like the updated DeftServerExample (multiple write, flush) (If its @Asynchronous or not is probably not the important thing.)

**Comment by jimpetersson** [comment]
Added some tests in DeftSystemTests.
Take a look and see if we need to add more tests. If not we could close this issue

**Comment by rschildmeijer** [comment]
looks nice

**Comment by jimpetersson** [comment]
Closed.
