### ISSUE TITLE
Simple HTTP GET request/response

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#4]
Using e.g "curl http://localhost:8080/"
response: "hello world"

**Comment by rschildmeijer** [comment]
A http request message consist of the following parts: 
<request-line>
<general-headers>
<request-headers>
<entity-headers>
<empty-line>
[<message-body>]
[<message-trailers>](from http://bit.ly/c9Oteh)

Basic Rules for Http Message "Parsing": http://bit.ly/9zpN2M

**Comment by rschildmeijer** [comment]
An example of a (GET) response (using fiddler and made a request against a running tornado web server on the LAN):
HTTP/1.1 302 Found
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Location: /auth/login?next=%2F
Server: TornadoServer/1.0.1

Content-Type and Location are (?) RH implementation details

**Comment by jimpetersson** [comment]
Done
