### ISSUE TITLE
Deft web page

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#40]
Get a simple version of a web page for deft up and running.
Create account on Google App Engine (GAE) and try to host it there

**Comment by rschildmeijer** [comment]
www.deftserver.org, deployed on GAE

**Comment by rschildmeijer** [comment]
initial draft up for review.

**Comment by schildmeijer** [comment]
removed documentation from README. (deftserver.org is the new black). closed by 4a4fddbe9d99430a3ef48f7b4ba208e2f187f57f
