### ISSUE TITLE
Chain support in HttpResponse.write

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#41]
The last callback in an asynchronous callback chain will often look something like this
response.write(result); 
response.finish(); 

If write "returns this" the above could be written:

response.write(result).finish();

**Comment by rschildmeijer** [comment]
pros/cons?

**Comment by jimpetersson** [comment]
The only thing I could think of is if write instead should return the number of bytes written?

**Comment by jimpetersson** [comment]
Hmm, its more probably flush that should return bytes written. (Since write doesn't actually send anything along the wire).
Desgin proposal:
write: returns "this"
flush: returns number of bytes written
finish: returns number of bytes written

**Comment by rschildmeijer** [comment]
+1 on this

**Comment by jimpetersson** [comment]
Implemented chain support in HttpResponse.
Closed by 8bc87a51c82b991dfe23b240e1c83c83b4cb20c2
