### ISSUE TITLE
Default ByteBuffer (read) size

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#43]
"Ideally, an HTTP request should not go beyond 1 packet. The most widely used networks limit packets to approximately 1500 bytes, so if you can constrain each request to fewer than 1500 bytes, you can reduce the overhead of the request stream. HTTP request headers include:"
from: http://bit.ly/bkksUu

**Comment by jimpetersson** [comment]
Aha, nice, should we set default buffer size to 1500? We could also expose the buffer size parameter, so a client can change this value if needed.

**Comment by rschildmeijer** [comment]
yes and yes

**Comment by schildmeijer** [comment]
Implemented #43 (Default ByteBuffer (read) size). Default read buffer size is 1500 bytes. Closed by d7ce74cc2a0dd2aa4f2a14794da863072c1d06fb
