### ISSUE TITLE
Return NotFoundRequestHandler in Application.getHandler(String path)

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#45]
In HPI; application.getHandler(request.getRequestedPath()); could return a "default" (Not Found) RequestHandler if no request handler is mapped to the given path.

Code in HPI.handleRead could look much cleaner.

**Comment by schildmeijer** [comment]
Implemented #45 (Return NotFoundRequestHandler in Application.getHandler(String path)). Closed by 63ccb3b1620747132965c3ad96e68eb6cb943123
