### ISSUE TITLE
Header names should be case-insensitive

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#48]
The header name should not be case-sensitive (though the value may be).
We need to change methods like HttpRequest.getHeader(String name)

**Comment by rschildmeijer** [comment]
citation needed :)

**Comment by jimpetersson** [comment]
http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

**Comment by johnathanmeehan** [comment]
Ran a UT against the latest source and saw that the issue exists. Would like to look into this and correct it.

**Comment by jimpetersson** [comment]
Welcome Johnatan!
Sure go ahead and then submit a patch.

**Comment by rschildmeijer** [comment]
Deleted post by johnathanmeehan by mistake (readded below, sorry johnathan)

johnathanmeehan: 
"Patch submitted to mailing list, as I'm not at all sure what I am doing with Git and GitHub just yet. :)"

I am +-0 on the patch. The patch (solution) looks fine but I did some quick benchmarks before and after the patch was applied and noticed a performance drop with ~5-800 request/second (used ab -k -c10 -n250000 http://127.0.0.1:8080/ running org.deftserver.example.DeftServerExample, the interesting part is the delta (before patch and after patch)). 

I'm not sure we want to do this compromise to have this feature.

johnathanmeehan, please verify my quick benchmark with ab. 
I guess the switch from j.u.HashMap to j.u.TreeMap is the root of this performance drop. Also the additional copies that are made in the HttpRequest constructor
 (this.headers.putAll(headers); ) could be another issue (from the performance point of view).

**Comment by schildmeijer** [comment]
Implements #48 (Header names should be case-insensitive) (closed by e8d07a1790dc301fdfdf0142f96ba56bc90a9829)
patch by Johnathan Meehan reviewed by rschildmeijer
