### ISSUE TITLE
Create Maven release goal/lifecycle phase

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#49]
proposed structure:
deft-x.x.x.zip
  /lib (3rd part dep, e.g guava, logback, slf4j..etc)
  LICENSE.txt
  NEWS.txt
  NOTICE.txt
  README.md
  deft-x.x.x.jar

q: should we include the source?

**Comment by jimpetersson** [comment]
Looks good. I guess we could release a deft-x-x-x.zip and a deft-src-x-x-x.zip ?
Where deft-src could contain a /src folder

**Comment by jimpetersson** [comment]
Another suggestion would be:
Binary:
- deft-x-x-x.zip
- deft-x-x-x-deps.zip (with dependencies)

Source:
- deft-x-x-x-src.zip

**Comment by rschildmeijer** [comment]
dots intstead of hyphens between major minor micro version parts. otherwise its a good idea

**Comment by jimpetersson** [comment]
Three versions are now built by mvn assembly:assembly
- deft-x.x.x-binary.zip
- deft-x.x.x-binary-with-deps.zip
- deft-x.x.x-src.zip

**Comment by rschildmeijer** [comment]
guess this issue is finished then

**Comment by jimpetersson** [comment]
.
