### ISSUE TITLE
POST support

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#50]
Support for http method POST

naive introduction to POST : http://www.jmarshall.com/easy/http/#postmethod

**Comment by schildmeijer** [comment]
Implemented #50 (POST support) &amp; #71 (Verify that HttpProtocol.handleRead is correct) (closed by 74884e6d49b46b8f5a9f2a9857b61f0c9e1d9bed) (closed by 74884e6d49b46b8f5a9f2a9857b61f0c9e1d9bed)
