### ISSUE TITLE
Make parsing of HttpRequest more robust

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#54]
HttpRequest.of() must be able to handle "non-standard" formats.
For instance header definitions could end with just LF instead of CRLF.
It should also not crash if it receives garbage-data.

**Comment by rschildmeijer** [comment]
What bugs me most is the impact to HPI.handleRead(..). I cant come up with a solution that doesnt include an ugly if (request == null) {return; }...
(the connection is (could be) closed in HPI.getHttpRequest(..)).

pros / cons?

other design proposals are welcome

**Comment by schildmeijer** [comment]
Implemented #54 (Make parsing of HttpRequest more robust) (closed by 5b98dcff52e57a789cee0a8e6e3a2f5a2c3a3dc1)
