### ISSUE TITLE
Expose KEEP_ALIVE_TIMEOUT

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#57]
We should make the keep-alive-timeout parameter available for "clients"

**Comment by rschildmeijer** [comment]
github/sris mentioned that tornado is probably not using any timeout for keep-alive connections. good from a longpoll et.al perspective. but what about connection leakage?

**Comment by jimpetersson** [comment]
Could make so that settinge timeout-value to value < 1 means no timeout will be used

**Comment by rschildmeijer** [comment]
sounds reasonable. (default?)

**Comment by jimpetersson** [comment]
Sure

**Comment by schildmeijer** [comment]
Implemented #67 (Expose WRITE_BUFFER_SIZE ) and #57 (Expose KEEP_ALIVE_TIMEOUT) (closed by 6601460362c8a3e27984a17c296c7d6d615cba6e) (closed by 6601460362c8a3e27984a17c296c7d6d615cba6e)
