### ISSUE TITLE
HTTP Head support 

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#58]
Add support for HTTP HEAD method.
Should be implemented by StaticContentHandler

**Comment by rschildmeijer** [comment]
"A HEAD request is just like a GET request, except it asks the server to return the response headers only, and not the actual resource (i.e. no message body). This is useful to check characteristics of a resource without actually downloading it, thus saving bandwidth. Use HEAD when you don't actually need a file's contents.

The response to a HEAD request must never contain a message body, just the status line and headers. "

(from http://bit.ly/agQ17X)

**Comment by schildmeijer** [comment]
Implements #58 (HTTP Head support) (closed by 558639520efb079664f590190a47efdffc9e8b9f) patch by Johnathan
Meehan reviewed by rschildmeijer
