### ISSUE TITLE
Remove obsolete doc. (+ unit test)

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#59]
HttpResponse.write(File file) has obsolete documentation/javadoc. Remove.
Create a system test that creates a user defined version of StaticContentHandler and try sending a file with HttpResponse.write(file).

**Comment by schildmeijer** [comment]
Implemented #59 (Remove obsolete doc. (+ unit test)) (closed by 5e086049bb81c9ebcbe0554da9e02cc6f6195986) (minor modification to HP MXBean registration)
