### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#6]
java.util.logging, slf4j, log4j..?

**Comment by jimpetersson** [comment]
slf4j, with Logback as the implementation would be my suggestion

**Comment by rschildmeijer** [comment]
from SO: "Logback natively implements the SLF4J API. This means that if you are using logback, you are actually using the SLF4J API. You could theoretically use the internals of the logback API directly for logging, but that is highly discouraged. All logback documentation and examples are written in terms of the SLF4J API.

So by using logback, you'd be actually using SLF4J and if for any reason you wanted to switch back to log4j, you could do so within minutes by simply dropping slf4j-log4j12.jar onto your class path."

from logback (http://logback.qos.ch/): "Logback is intended as a successor to the popular log4j project, picking up where log4j leaves off. "

Fine by me.

**Comment by jimpetersson** [comment]
Done, see DeftServerExample.java for usage
