### ISSUE TITLE
Support for third party libraries to work within Deft's IOLoop

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#62]

**Comment by jimpetersson** [comment]
Need to investigate this further..

**Comment by rschildmeijer** [comment]
have a couple of patches (issue (75-100)% finished) (locally on my machine). would be nice to have some feedback.

**Comment by schildmeijer** [comment]
Introd
Initial "client side example code" for #62 (only scaffolding)

Added TimeoutManager interface and created an imlementor: LoadInferringTimeoutManager
Partial #62 (Introduced EventHandler concept to IOLoop, replace Protocol by EventHandler, added Simple (KeyValueStore) third party library example (work in progress)

Added callback support for read operation in KeyValueStore client example

Introduced Own Closeables.closeQuietly (wrapper for google guava's Closeables.closeQuitly + removing the IOHandler associated with the SelectableChannel that is about to be closed, to avoid memory leaks)

Added KeyValueStore system test

Updated NEWS.txt

(closed by 8203898dce02d3ab17c43cdbdaa2769c8005e760)
