### ISSUE TITLE
Expose WRITE_BUFFER_SIZE 

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#67]
Currently WRITE_BUFFER_SIZE is hard coded to 1500 (hint ~tcp packet)
This knob should be adjustable/configurable by clients.

**Comment by rschildmeijer** [comment]
I also propose a renaming. SIZE -> CAPACITY

**Comment by schildmeijer** [comment]
Implemented #67 (Expose WRITE_BUFFER_SIZE ) and #57 (Expose KEEP_ALIVE_TIMEOUT) (closed by 6601460362c8a3e27984a17c296c7d6d615cba6e) (closed by 6601460362c8a3e27984a17c296c7d6d615cba6e)
