### ISSUE TITLE
Verify that HttpResponse.[allocate, prepend, ensureCapacity] works as intended

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#69]

**Comment by schildmeijer** [comment]
Implemented #65 (Optimize ByteBuffer usage in critial write path) and #69 (Verify that HttpResponse.[allocate, prepend, ensureCapacity] works as intended) (closed by f5486845cd17c76563f1a8a385b275c6ce162edf closed by f5486845cd17c76563f1a8a385b275c6ce162edf)
