### ISSUE TITLE
Get rid of the explicit staging mechanism 

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#70]
Use SelectionKey attachment (attach a ByteBuffer) instead.

**Comment by rschildmeijer** [comment]
the file staging (used by SCH) is the "only" explicit staging mechanism left.

**Comment by schildmeijer** [comment]
Implemented #74 (Make use of the fact that a java.nio.SocketChannel always is writable if SO_SNDBUF is > 0) and #70 (Get rid of the explicit staging mechanism) (closed by a91924513fd75c63cb769f87843dae9bd36d3c84) (closed by a91924513fd75c63cb769f87843dae9bd36d3c84)
