### ISSUE TITLE
Verify that HttpProtocol.handleRead is correct

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#71]
We have a potential bug when reading/parsing a request.
If the clientChannel.read(buffer) is performed async, we cannot be sure that all data has been read when we start parsing the HttpRequest.
Before we start the parsing, we need to make sure that all data is read

**Comment by schildmeijer** [comment]
Implemented #50 (POST support) &amp; #71 (Verify that HttpProtocol.handleRead is correct) (closed by 74884e6d49b46b8f5a9f2a9857b61f0c9e1d9bed) (closed by 74884e6d49b46b8f5a9f2a9857b61f0c9e1d9bed)
