### ISSUE TITLE
Create more non blocking system test

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#72]
Most (all?) system test (see DeftSystemTest) is using blocking http request using apache httpcomponents. Its possible to use non blocking http client with apache hc. Also, could be worth add some tests that use ngin (http://github.com/AsyncHttpClient/async-http-client) async http client. (wider test scoop)

**Comment by rschildmeijer** [comment]
- test with large repsonse entity (>100kb, > WRITE_BUFFER_SIZE is probably a good idea to have system tests for also)

**Comment by schildmeijer** [comment]
#82 (Premature closing request in HttpResponse.finish()) (closed by 8c308f51759dd826c82281da0c6e7ea19e52cf69)
#72 (Create more non blocking system test) (closed by 8c308f51759dd826c82281da0c6e7ea19e52cf69)
