### ISSUE TITLE
Make use of the fact that a java.nio.SocketChannel always is writable if the underlaying socket write buffers is not full

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#74]
Like we did in deft 0.1.0 / 0.1.1. In HttpResponse.write we tried send data to the channel directly, instead of register for write io events.
(if we cant send all data we still need to register for a write io event/callback)

**Comment by schildmeijer** [comment]
Implemented #74 (Make use of the fact that a java.nio.SocketChannel always is writable if SO_SNDBUF is > 0) and #70 (Get rid of the explicit staging mechanism) (closed by a91924513fd75c63cb769f87843dae9bd36d3c84) (closed by a91924513fd75c63cb769f87843dae9bd36d3c84)
