### ISSUE TITLE
Support for large static files

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#75]
Currently we cant handle large files (~>200kb).

**Comment by rschildmeijer** [comment]
I have a (working, quick fix) hacky solution for this (in HttpResponse.write(File file)): 
    long bytesWritten = 0;  
    while (bytesWritten < file.length()) {
        bytesWritten += new RandomAccessFile(file,"r").getChannel().transferTo(bytesWritten, file.length(), (SocketChannel) key.channel());
        try {
            Thread.sleep(10);   // TODO RS 101026 Quick fix to support large static files
        } catch (InterruptedException e) { logger.error("Interruted during sleep: {}",   e.getMessage()); }
    }

**Comment by johnathanmeehan** [comment]
That didn't work at all for me :(. I had to look at chunking the output:

RandomAccessFile random = new RandomAccessFile(file, "r");
FileChannel channel = random.getChannel();
MappedByteBuffer mb = channel.map(MapMode.READ_ONLY, 0L, channel.size());
while(mb.hasRemaining()) {
    ((SocketChannel) key.channel()).write(mb);
}

**Comment by rschildmeijer** [comment]
the above solved your problem? (If) I'm still -1 on the solution because of the busy/wait

**Comment by 1730wang** [comment]
I have a weird problem. There is a 30kb css file.
On my windows box, it works perfectly.
On my linux box, it always hangs at exactly 10kb. (browser only shows 1/3 of the css content and keeps waiting for about 30 seconds then closes the connection)

**Comment by 1730wang** [comment]
johnathanmeehan's solution fixed my problem.

**Comment by rschildmeijer** [comment]
be aware that its a busy wait solution because of the while(mb.hasRemaining()) {..}
a more appropriate solution would be to "stage" the MappedByteBuffer (if you didnt send everything in the first write attempt) (something like key.attachment(mbb)) in HttpResponse.write and write as much as possible in every HttpProtocol.handleWrite callback

**Comment by 1730wang** [comment]
Ok, I've made some changes based on rschildmeijer's suggestion:

In HttpResponse class:

```
public long write(File file) {
    setHeader("Content-Length", String.valueOf(file.length()));
    long bytesWritten = 0;
    flush(); // write initial line + headers
    try {
        RandomAccessFile raf = new RandomAccessFile(file, "r");
        FileChannel fc = raf.getChannel();
        long fsize = fc.size();
        MappedByteBuffer mbb = fc.map(MapMode.READ_ONLY, 0L, fsize);
        if (mbb.hasRemaining()) {
            ((SocketChannel) key.channel()).write(mbb);
        }
        if (mbb.hasRemaining()) {
            try {
                key.channel().register(key.selector(),
                        SelectionKey.OP_WRITE);
            } catch (ClosedChannelException e) {
                Closeables.closeQuietly(key.channel());
            }
            key.attach(mbb);
        }
    } catch (IOException e) {}
    return bytesWritten;
}
```

And in HttpProtocol class:

```
public void handleWrite(SelectionKey key) {
    SocketChannel channel = ((SocketChannel) key.channel());
    try {
        if (key.attachment() instanceof MappedByteBuffer) {
            MappedByteBuffer mbb = (MappedByteBuffer) key.attachment();
            if (mbb.hasRemaining()) {
                channel.write(mbb);
            }
            if (IOLoop.INSTANCE.hasKeepAliveTimeout(channel)) {
                prolongKeepAliveTimeout(channel);
            }
            if (!mbb.hasRemaining()) {
                Closeables.closeQuietly(key.channel());
            }
        } else if (key.attachment() instanceof DynamicByteBuffer) {
            DynamicByteBuffer dbb = (DynamicByteBuffer) key.attachment();
            ByteBuffer toSend = dbb.getByteBuffer();
            toSend.flip(); // prepare for write
            long bytesWritten = channel.write(toSend);
            if (IOLoop.INSTANCE.hasKeepAliveTimeout(channel)) {
                prolongKeepAliveTimeout(channel);
            }
            Logger.logDebug(HttpProtocol.class.getSimpleName(),
                    "sent {} bytes to wire" + bytesWritten);
            if (!toSend.hasRemaining()) {
                Logger.logDebug(HttpProtocol.class.getSimpleName(),
                        "sent all data in toSend buffer");
                closeOrRegisterForRead(key); // should probably only be done
                                                // if
                                                // the HttpResponse is
                                                // finished
            } else {
                toSend.compact(); // make room for more data be "read" in
            }
        }
    } catch (IOException e) {
        Closeables.closeQuietly(key.channel());
    }
}
```

And it works great!

Thanks rschildmeijer!!!

p.s. Changes are committed:

https://github.com/1730wang/deft/commit/99568ba81b230fdd8f936f63c2cda5673ef71ab7#src/main/java/org/deftserver/web/http/HttpProtocol.java

https://github.com/1730wang/deft/commit/1a5ed71110fe2453f616d248937cfd79dc14a015#src/main/java/org/deftserver/web/http/HttpResponse.java

**Comment by rschildmeijer** [comment]
review in queue...

**Comment by ilmich** [comment]
Great, but keep in mind the issue #135 :)

Thanks

**Comment by 1730wang** [comment]
I guess I need to attach an object array to key like this { raf, mbb }?

**Comment by rschildmeijer** [comment]
1730wang: not sure I follow you. collaborate

**Comment by 1730wang** [comment]
rschildmeijer, 
ilmich mentioned the file handles not being closed issue(issue #135). 
I was thinking using key.attach(new Object[] { fileHandle, mbb }) instead of key.attach(mbb), and the fileHandle can be closed when mbb has no remaining.

**Comment by rschildmeijer** [comment]
Its safe to close the FileChannel after:
    MappedByteBuffer mbb = fc.map(MapMode.READ_ONLY, 0L, fsize);

Javadoc from FileChannel.map:
"A mapping, once established, is not dependent upon the file channel that was used to create it. Closing the channel, in particular, has no effect upon the validity of the mapping. "

Also, the first if check:
        if (mbb.hasRemaining()) {
            ((SocketChannel) key.channel()).write(mbb);
        }
is probably redudant. Could safely be removed. (or atleast check against fsize)

When you have fixed this feel free to supply a patch (here or on the mailing list) and I will review + commit the changes :)

**Comment by 1730wang** [comment]
Oh, cool! I was scanning through it but just escaped this sentence !^_^

Thanks!

**Comment by rschildmeijer** [comment]
committed to master. thanks 1730wang!
