### ISSUE TITLE
IOC

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#8]
Might be nice to use an "IOC-container", Spring Guice..

**Comment by rschildmeijer** [comment]
I'm -1 on introducing Spring.
Guice could be worth a try. 

What itches my back is that I'm not aware of a single (successful) open source project that uses Guice.
Did a quick google and the only thing I came up with was this: "Maven to be built on Guice" (http://bit.ly/aCAFUa)
Also did a quick, highly scientific survey -- I browsed the apace SVN repository and looked deeper into a couple of arbitrary projects. (0 hits).

But afterall, It's ok with me to give Guice a chance.

**Comment by rschildmeijer** [comment]
close? won't fix :) ?

**Comment by jimpetersson** [comment]
I agree, we close this for now.
