### ISSUE TITLE
Fast timeouts

### ISSUE THREAD

**Issue by williame** [rschildmeijer/deft#80]
assumption is that timeout management will become an increasing proportion of the time as the server scales; investigate timeouts and assure us we have a best-possible approach

**Comment by rschildmeijer** [comment]
I totaly agree. 
    org.deftserver.io.TimeoutManager 
and the concrete impl 
    JMXConfigurableTimeoutManager 
is supposed to address this issue. 

Some initial thoughts (jmx configration knobs).
1, max time spent per iteration (to avoid io(loop) starvation) 
2, max number of timeouts per iteration.
3, dynamic timeout manager. w.r.t. to the load (inspired by DynamicEndPointSnitch in cassandra)

**Comment by schildmeijer** [comment]
Implemented #80 (Fast timeouts) (closed by 1116709df55276a5f2eb11f5b8071846359c88ca)
