### ISSUE TITLE
Premature closing request in HttpResponse.finish()

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#82]
we are doing that (closeOrRegisterForRead) every time (no if condition). we are not sure that everything in responseData is sent to wire. Previously we could have registered for writing (because we could not send all data in flush(), write buffer was too small compared to the "big" responsedata.)

**Comment by rschildmeijer** [comment]
Ugly solution (in HttpResponse.finish, replace protocol.closeOrRegisterForRead(key); (~row 90) with): 
    // close (or reg for read) iff. 
    // (a) DBB is attached but all data is sent to wire (hasRemaining == false)
    // (b) no DBB is attached
    if (key.attachment() instanceof DynamicByteBuffer) {
        if (!((DynamicByteBuffer)key.attachment()).hasRemaining()) {
            protocol.closeOrRegisterForRead(key);
        } 
    } else {  
        protocol.closeOrRegisterForRead(key);
    }

**Comment by rschildmeijer** [comment]
No measured performance decrease (bm on imac)

**Comment by schildmeijer** [comment]
#82 (Premature closing request in HttpResponse.finish()) (closed by 8c308f51759dd826c82281da0c6e7ea19e52cf69)
#72 (Create more non blocking system test) (closed by 8c308f51759dd826c82281da0c6e7ea19e52cf69)
