### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#83]
inspiration: http://www.tornadoweb.org/documentation#user-authentication

**Comment by rschildmeijer** [comment]
patch up for review on ml: http://groups.google.com/group/deft-web-server/browse_thread/thread/a5345e8c01124d97#

**Comment by schildmeijer** [comment]
Implements #83 (Authentication) (closed by db5a039e18fed7e923647315e6b77624e7ef2d53)
