### ISSUE TITLE
Timeout priorities

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#86]
facebook/tornado exerts itself to satify the timeouts added to the IOLoop.
eg.
while True:
    poll_timeout = 0.2
    [ ... ]
    if self._timeouts:
        now = time.time()
        while self._timeouts and self._timeouts[0].deadline <= now:
            timeout = self._timeouts.pop(0)
            self._run_callback(timeout.callback)
        if self._timeouts:
            milliseconds = self._timeouts[0].deadline - now
            poll_timeout = min(milliseconds, poll_timeout)

the last row is interesting. the poll_timeout (TIMEOUT in deft) is modified so the next timeout will be executed as soon as possible.

**Comment by rschildmeijer** [comment]
patch submitted for review

**Comment by schildmeijer** [comment]
Implements #89 (Timeouts added during timeouts) &amp; #86 (Timeout
priorities) (closed by 631a8cf357e8d6391dd14cfacfce3fafb079ea3a) (closed by 631a8cf357e8d6391dd14cfacfce3fafb079ea3a)
