### ISSUE TITLE
Source/Test Package Relationships

### ISSUE THREAD

**Issue by johnathanmeehan** [rschildmeijer/deft#92]
The packages for test types are not in sync. with the source. For example, the type org.deftserver.web.http.HttpRequest is under test by the FQCN org.deftserver.web.HttpRequestTest. This should be corrected, with the test package being moved to match the source.

**Comment by johnathanmeehan** [comment]
I am looking into this.

**Comment by schildmeijer** [comment]
Implements #92 (Source/Test Package Relationships) (closed by 62d91d5a026c0312872cf537d4ce2a2a7b186547), patch
by johnathanmeehan reviewed by rschildmeijer
