### ISSUE TITLE
Timeout removal

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#94]
Add support for removal of (obsolete) timeouts. 
hint: IOLoop#removeTimeout(Timeout timeout)

**Comment by rschildmeijer** [comment]
working on this

**Comment by rschildmeijer** [comment]
patch available on ml

http://groups.google.com/group/deft-web-server/browse_thread/thread/e571d4bbcb23abb3

**Comment by schildmeijer** [comment]
Implements #94 (Timeout removal) (closed by 1e37307c942861928c743c8cc110b1affc7cec84)
